version: '3.2'
services:
  backend1:
    build: ./backend
    tty: true
    volumes: 
      - './backend/src:/backend-dir-inside-container'
    environment:
      - INSTANCE=backend1
    

  backend2:
    build: ./backend
    tty: true
    volumes: 
      - './backend/src:/backend-dir-inside-container'
    environment:
      - INSTANCE=backend2

  backend3:
    build: ./backend
    tty: true
    volumes: 
      - './backend/src:/backend-dir-inside-container'
    environment:
      - INSTANCE=backend3

  loadbalancer:
    build: ./load-balancer
    tty: true
    links: 
      - backend1
      - backend2
      - backend3
    ports:
      - '8080:8080'

volumes:
  backend: